Repository GIScience/sketch-map-tool, pull requests merged in 2022-10, with the labels that each got.

#59 Fix analyses with new project layout
  CHANGELOG.MD
  sketch_map_tool/analyses/pdf_gen/pdf_gen.py
  sketch_map_tool/analyses/run_analyses.py
  sketch_map_tool/app.py
  sketch_map_tool/constants.py
Labels: bug, component:analyses, waiting for review

#71 Add package json to run node packages locally
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  docs/development-setup.md
  package-lock.json
  package.json
Labels: code quality

#79 fix misaligned arrows in index2.html, especially when scaling the page
  sketch_map_tool/static/style/base.css
  sketch_map_tool/static/style/index.css
  sketch_map_tool/templates/index2.html
Labels: component:website

#32 ci: run python tests
  .github/workflows/python.yml
  CHANGELOG.md
Labels: CI

#86 Poll status for downloads
  .eslintrc.json
  sketch_map_tool/data_store/client.py
  sketch_map_tool/routes.py
  sketch_map_tool/static/scripts/create-results/index.js
  sketch_map_tool/static/scripts/shared/domHelpers.js
  sketch_map_tool/static/scripts/shared/index.js
  sketch_map_tool/static/scripts/shared/poll/handleMainMessage.js
  sketch_map_tool/static/scripts/shared/poll/index.js
  sketch_map_tool/static/scripts/shared/poll/poll.js
  sketch_map_tool/static/scripts/shared/poll/pollUntilValid.js
  sketch_map_tool/tasks.py
  sketch_map_tool/templates/create-results.html
Labels: component:website
