Repository GIScience/sketch-map-tool, pull requests merged in 2023-04, with the labels that each got.

#237 Close #201: validate UUID when reading qr code and handle errors
  sketch_map_tool/upload_processing/qr_code_reader.py
  tests/fixtures/qr-codes/qr-code-invalid-contents.jpg
  tests/fixtures/qr-codes/qr-code-invalid-uuid.jpg
  tests/unit/upload_processing/test_qr_code_reader.py
Labels: component:upload-processing

#241 Fix #198: Name GeoTIFF after the name of the uploaded file
  sketch_map_tool/routes.py
  sketch_map_tool/tasks.py
Labels: component:upload-processing

#247 Delete outdated sketch_map_tool\constants.py
  sketch_map_tool/constants.py
Labels: code quality

#252 Update contact email
  sketch_map_tool/templates/about.html
Labels: component:website
